version: "2"
services:
  jellyfin:
    image: linuxserver/jellyfin #?use original or this one? jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
      - LC_ALL=en_US.UTF-8
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - JELLYFIN_MEDIA_DIR=/media
      - JELLYFIN_DATA_DIR=/config
      - JELLYFIN_CACHE_DIR=/cache
      - JELLYFIN_CONFIG_DIR=/config/config
      - JELLYFIN_LOG_DIR=/config/log
      - JELLYFIN_WEB_DIR=/jellyfin/jellyfin-web
      - JELLYFIN_FFMPEG=/usr/lib/jellyfin-ffmpeg/ffmpeg
    volumes:
      - /mediaNFS:/media:ro #?mount read only?
      - /host/jellyfin/transcode:/transcode
      - /host/tv:/tv
      - /host/movies:/movies
      # need to add a config on the ZFS drive here
      # ?see about putting transcode on ram (likely the default). 
    ports:
      - 8097:8096
      - 8921:8920 #what is this port
    restart: unless-stopped